apiVersion: v1
kind: Service
metadata:
  name: streamlit-app-service
spec:
  type: LoadBalancer # Or NodePort for local testing if LoadBalancer is not supported
  selector:
    app: streamlit-app
  ports:
    - protocol: TCP
      port: 8501
      targetPort: 8501